// <auto-generated />
namespace BancoNix.TransferenciaAPI.AcessaDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterColumn_Transferencia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumn_Transferencia));
        
        string IMigrationMetadata.Id
        {
            get { return "201802250225379_AlterColumn_Transferencia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
